# https://docs.docker.com/compose/compose-file/
# https://github.com/docker/awesome-compose
services:
  test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile.test
    volumes:
      - ./test_results:/app/test_results/
    entrypoint: pytest . --verbose --junit-xml=test_results/junit.xml --cov=cr_scraper --cov-report xml:test_results/coverage.xml
  lint:
    build:
      context: .
      dockerfile: docker/test/Dockerfile.test
    entrypoint: ./entrypoint.flake8.sh
  format:
    build:
      context: .
      dockerfile: docker/test/Dockerfile.test
    entrypoint: black . --check
  db-migration:
    build:
      context: .
      dockerfile: docker/test/Dockerfile.test
    environment:
      - DB_NAME=cr-scraper
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db-for-migration
      - DB_PORT=5432
    entrypoint: alembic upgrade head
    depends_on:
      db-for-migration:
        condition: service_healthy
  db-for-migration:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=cr-scraper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
