# https://docs.docker.com/compose/compose-file/
# https://github.com/docker/awesome-compose
services:
  test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile.test
    volumes:
      - ./test_results:/app/test_results/
    entrypoint: pytest . --verbose --junit-xml=test_results/junit.xml
  lint:
    build:
      context: .
      dockerfile: docker/test/Dockerfile.test
    entrypoint: ./entrypoint.flake8.sh
  format:
    build:
      context: .
      dockerfile: docker/test/Dockerfile.test
    entrypoint: black . --check
