# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Check code formatting with Black
        run: |
          docker-compose -f compose.test.yaml up --exit-code-from format format
          exit $?
      - name: Lint with flake8
        if: success() || failure() # always run even if the previous step fails
        run: |
          docker-compose -f compose.test.yaml up --exit-code-from lint lint
          exit $?
      - name: Test with pytest
        if: success() || failure()
        run: |
          docker-compose -f compose.test.yaml up --exit-code-from test test
          exit $?
      - name: Test database migration
        if: success() || failure()
        run: |
          docker-compose -f compose.test.yaml up --exit-code-from db-migration db-migration
          exit $?
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: "**/test_results/junit.xml"
          detailed_summary: true
          include_passed: true
      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: test_results/coverage.xml
          token: ${{ secrets.COVERAGE_TOKEN }}
